# SPDX-License-Identifier: Apache-2.0
"""Managed AGENTS.md guidance for resource accounting."""
from __future__ import annotations

import os
import re

from .wiring_common import read_text, strip_region

AGENTS_BEGIN = ("<!-- BEGIN llm_resource_tally v{version} (managed block — regenerated by "
                "`install`; edits below will be overwritten) -->")
AGENTS_END = "<!-- END llm_resource_tally -->"
AGENTS_BEGIN_RE = re.compile(
    r"<!--\s*BEGIN llm_resource_tally(?:\s+v([0-9][0-9A-Za-z.\-+]*))?.*?-->", re.S)


def _storage_guidance(mode: str) -> str:
    if mode == "committed":
        return ("The hook intentionally updates `.llm_resource_tally/`; these generated ledger, "
                "rollup, and badge changes are expected bookkeeping. Do not spend time "
                "investigating, reverting, rewriting, or cleaning them up unless a tally command "
                "reports an error; include intended accounting changes with an ordinary commit.")
    if mode == "ignored":
        return ("Accounting files under `.llm_resource_tally/` are intentionally local and "
                "gitignored. Leave them alone; they require no staging, review, or cleanup.")
    return ("Measured rows are intentionally stored in `refs/notes/llm-resource-tally`, with "
            "mutable settings and reports below the git directory. They require no worktree "
            "staging or review.")


def _install_guidance(run: str, mode: str) -> str:
    suffix = f" --storage {mode}" if mode != "committed" else ""
    return f"After cloning, run `{run} install{suffix}` once to arm git-local hooks."


def managed_agents_block(run: str, version: str, mode: str = "committed") -> str:
    snippet = f"""## LLM resource accounting
A git hook records measured token/model usage for commits and a Claude SessionEnd hook can sweep
non-committing work. {_storage_guidance(mode)}

{_install_guidance(run, mode)} Do not hand-edit or hand-count ledger rows. Use `{run} doctor`
when accounting itself appears unhealthy; otherwise continue the repository task normally."""
    return AGENTS_BEGIN.format(version=version) + "\n" + snippet + "\n" + AGENTS_END


def install_agents_block(root: str, run: str, version: str, agents_name: str,
                         mode: str = "committed") -> str:
    path = os.path.join(root, agents_name)
    block = managed_agents_block(run, version, mode)
    if os.path.exists(path):
        text = read_text(path)
        m = AGENTS_BEGIN_RE.search(text)
        if m and AGENTS_END in text[m.end():]:
            old = m.group(1) or "?"
            e = text.index(AGENTS_END, m.end()) + len(AGENTS_END)
            new_text = text[:m.start()] + block + text[e:]
            if new_text == text:
                return f"already current (v{version})"
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_text)
            return (f"regenerated managed block (v{version})" if old == version
                    else f"upgraded managed block v{old} -> v{version}")
        sep = "\n" if text.endswith("\n") else "\n\n"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text + sep + block + "\n")
        return f"appended managed block (v{version})"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"# {agents_name}\n\n" + block + "\n")
    return f"created {agents_name} with managed block (v{version})"


def uninstall_agents_block(root: str, agents_name: str) -> str | None:
    path = os.path.join(root, agents_name)
    if not os.path.exists(path):
        return None
    text = read_text(path)
    m = AGENTS_BEGIN_RE.search(text)
    if m and AGENTS_END in text[m.end():]:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(strip_region(text, m.start(), AGENTS_END))
        return f"stripped managed block from {agents_name}"
    return None
