# SPDX-License-Identifier: Apache-2.0
"""Managed AGENTS.md guidance for resource accounting."""

from __future__ import annotations

import os
import re
import textwrap

from .wiring_common import read_text, strip_region

AGENTS_BEGIN = (
    "<!-- BEGIN llm_resource_tally v{version} (managed block — regenerated by "
    "`install`; edits below will be overwritten) -->"
)
AGENTS_END = "<!-- END llm_resource_tally -->"
AGENTS_BEGIN_RE = re.compile(r"<!--\s*BEGIN llm_resource_tally(?:\s+v([0-9][0-9A-Za-z.\-+]*))?.*?-->", re.S)


WRAP_WIDTH = 98
_CODE_SPAN = re.compile(r"`[^`]+`")
_NOBREAK = "\x00"  # stands in for a space inside a code span while textwrap runs


def _fill(text: str, **kwargs) -> str:
    """Wrap prose without ever splitting a `code span` — a broken command cannot be copy-pasted."""
    protected = _CODE_SPAN.sub(lambda m: m.group(0).replace(" ", _NOBREAK), text)
    filled = textwrap.fill(protected, width=WRAP_WIDTH, break_long_words=False, **kwargs)
    return filled.replace(_NOBREAK, " ")


def _storage_guidance(mode: str) -> str:
    """Where measured rows land, and what that means for the worktree the agent is working in."""
    if mode == "local":
        return (
            "Rows and mutable rollups are written under `.llm_resource_tally/local/`, which is "
            "gitignored. Recording therefore never modifies a tracked file and never blocks a "
            "commit, merge, rebase, or stash."
        )
    if mode == "committed":
        return (
            "The hook intentionally updates tracked files under `.llm_resource_tally/`. Those "
            "ledger, rollup, and badge changes are expected bookkeeping — include them in an "
            "ordinary commit rather than investigating or reverting them."
        )
    if mode == "ignored":
        return (
            "Everything generated under `.llm_resource_tally/` is gitignored except "
            "`.llm_resource_tally/settings.json`, which is the committed installation policy."
        )
    return (
        "Rows are stored in `refs/notes/llm-resource-tally` and mutable reports live below the "
        "git directory, so the worktree stays clean. Notes are not fetched or pushed by default; "
        "sync that ref explicitly when sharing."
    )


def _publish_guidance(run: str, mode: str) -> str | None:
    """Local mode spools to an ignored path, so publication is the step that lands accounting."""
    if mode != "local":
        return None
    return (
        f"**Publish before you hand off substantial work.** Run `{run} publish`: it snapshots local "
        "rows onto the tracked append-only ledger under `.llm_resource_tally/ledger/` and "
        "refreshes the tracked `lifetime-totals.json` and `badge.json`. Stage and commit what it "
        "writes, preferably as its own commit so accounting stays out of unrelated diffs. This is "
        "routine — nobody should have to remember to ask you for it, and unpublished rows exist "
        "only on this machine."
    )


def managed_agents_block(run: str, version: str, mode: str = "local") -> str:
    bullets = [
        _storage_guidance(mode),
        "Never hand-edit, hand-count, revert, or clean up ledger rows, and never let accounting "
        "block the repository work you were asked to do. Recording is best-effort by design.",
        _publish_guidance(run, mode),
        f"If accounting itself looks unhealthy, run `{run} doctor` — it checks hook wiring, "
        "backends, transcript retention, and ledger health, and names what to fix. Otherwise "
        "continue the repository task normally.",
        f"After a fresh clone, run `{run} install` once to arm git-local hooks. It is offline and "
        "idempotent, and it reads the committed `.llm_resource_tally/settings.json` policy.",
    ]
    body = "\n".join(_fill(b, initial_indent="- ", subsequent_indent="  ") for b in bullets if b)
    snippet = (
        "## LLM resource accounting\n"
        + _fill(
            "A git post-commit hook — and Claude Code hooks when wired — records the measured "
            "token and model usage this repository costs. It is automatic bookkeeping and is not "
            "part of whatever task you were given."
        )
        + "\n\n"
        + body
    )
    return AGENTS_BEGIN.format(version=version) + "\n" + snippet + "\n" + AGENTS_END


def install_agents_block(root: str, run: str, version: str, agents_name: str, mode: str = "local") -> str:
    path = os.path.join(root, agents_name)
    block = managed_agents_block(run, version, mode)
    if os.path.exists(path):
        text = read_text(path)
        m = AGENTS_BEGIN_RE.search(text)
        if m and AGENTS_END in text[m.end() :]:
            old = m.group(1) or "?"
            e = text.index(AGENTS_END, m.end()) + len(AGENTS_END)
            new_text = text[: m.start()] + block + text[e:]
            if new_text == text:
                return f"already current (v{version})"
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_text)
            return (
                f"regenerated managed block (v{version})"
                if old == version
                else f"upgraded managed block v{old} -> v{version}"
            )
        sep = "\n" if text.endswith("\n") else "\n\n"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text + sep + block + "\n")
        return f"appended managed block (v{version})"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"# {agents_name}\n\n" + block + "\n")
    return f"created {agents_name} with managed block (v{version})"


def uninstall_agents_block(root: str, agents_name: str) -> str | None:
    path = os.path.join(root, agents_name)
    if not os.path.exists(path):
        return None
    text = read_text(path)
    m = AGENTS_BEGIN_RE.search(text)
    if m and AGENTS_END in text[m.end() :]:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(strip_region(text, m.start(), AGENTS_END))
        return f"stripped managed block from {agents_name}"
    return None
