# SPDX-License-Identifier: Apache-2.0
"""Git hook and storage-related worktree wiring."""

from __future__ import annotations

import os
import shutil
import subprocess

from .gitutil import git
from .vendoring import is_source_checkout_path
from .wiring_common import chmod_x, git_config, read_text, replace_region

HOOK_BEGIN = "# >>> llm_resource_tally (managed — regenerated by `install`) >>>"
HOOK_END = "# <<< llm_resource_tally (managed) <<<"

TOOL_GITIGNORE = (
    "# llm_resource_tally: the vendored tool runs in place; ignore its bytecode\n__pycache__/\n*.pyc\n"
)

GITIGNORE_BEGIN = "# >>> llm_resource_tally local state (managed) >>>"
GITIGNORE_END = "# <<< llm_resource_tally local state (managed) <<<"
LEGACY_GITIGNORE_BEGIN = "# >>> llm_resource_tally ignored storage (managed) >>>"
LEGACY_GITIGNORE_END = "# <<< llm_resource_tally ignored storage (managed) <<<"


LEGACY_TALLY_HOOKSPATHS = (
    ".llm_resource_tally/hooks",
    ".llm_resource_tally/tool/hooks",
    ".llm_resource_tally-hooks",
)


def _is_legacy_tally_hookspath(value: str) -> bool:
    return bool(
        value and os.path.normpath(value) in {os.path.normpath(path) for path in LEGACY_TALLY_HOOKSPATHS}
    )


def _remove_legacy_tally_hooks(root: str, hooks_path: str) -> bool:
    """Remove the old tally-owned worktree hook directory when it is safe to do so."""
    if not _is_legacy_tally_hookspath(hooks_path):
        return False
    path = hooks_path if os.path.isabs(hooks_path) else os.path.join(root, hooks_path)
    if not os.path.isdir(path):
        return False
    entries = set(os.listdir(path))
    if entries - {"post-commit"}:
        return False
    hook = os.path.join(path, "post-commit")
    if os.path.exists(hook):
        hook_text = read_text(hook)
        if "llm_resource_tally" not in hook_text:
            return False
    shutil.rmtree(path)
    return True


def ensure_tool_gitignore(root: str, rel: str) -> None:
    """Keep bytecode out of a source install; zipapps cannot create package-local bytecode."""
    artifact = os.path.join(root, rel)
    if is_source_checkout_path(root, rel) or os.path.isfile(artifact) or rel.endswith(".pyz"):
        return
    p = os.path.join(artifact, ".gitignore")
    if not os.path.exists(p):
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(TOOL_GITIGNORE)


def _hook_block(rel: str) -> str:
    return (
        f"{HOOK_BEGIN}\n"
        f'root="$(git rev-parse --show-toplevel 2>/dev/null)" || root=""\n'
        f'[ -n "$root" ] && python3 -B "$root/{rel}" record '
        f"--commit HEAD >/dev/null 2>&1 || true\n"
        f"{HOOK_END}"
    )


def hooks_dir_default(root: str) -> str:
    hd = git("rev-parse", "--git-path", "hooks", cwd=root)
    return hd if os.path.isabs(hd) else os.path.join(root, hd)


def effective_hooks_dir(root: str, existing_hp: str) -> str:
    if existing_hp:
        return existing_hp if os.path.isabs(existing_hp) else os.path.join(root, existing_hp)
    return hooks_dir_default(root)


def wire_hook(root: str, rel: str, mode: str, hooks_rel: str | None = None) -> str:
    """Install the managed block into Git-local hooks, respecting custom hook paths.

    Older releases configured ``core.hooksPath`` to a generated directory in the worktree.
    Auto-install now migrates that tally-owned path back to Git's normal hook directory so the
    only ignored worktree state is accounting data beneath ``.llm_resource_tally/local``.
    ``hooks_rel`` is retained for API compatibility with older callers and is ignored.
    """
    del hooks_rel
    if mode == "none":
        return "skipped (--hook-mode none)"

    existing_hp = git_config(root, "--get", "core.hooksPath")
    migrated = ""
    if _is_legacy_tally_hookspath(existing_hp):
        git("config", "--unset", "core.hooksPath", cwd=root)
        removed = _remove_legacy_tally_hooks(root, existing_hp)
        migrated = f"migrated tally-owned core.hooksPath {existing_hp} to Git-local hooks; "
        if not removed:
            migrated += "left nonstandard legacy hook directory in place; "
        existing_hp = ""

    # ``hookspath`` remains accepted for command-line compatibility, but no longer creates a
    # generated hook directory in the worktree. A preexisting user-configured core.hooksPath is
    # still honored; otherwise Git's normal per-repository hooks directory is used.
    message = _append_hook(root, rel, existing_hp)
    return migrated + message


def _append_hook(root: str, rel: str, existing_hp: str) -> str:
    hd = effective_hooks_dir(root, existing_hp)
    os.makedirs(hd, exist_ok=True)
    hook = os.path.join(hd, "post-commit")
    where = os.path.relpath(hook, root)
    block = _hook_block(rel)
    if os.path.exists(hook):
        text = read_text(hook)
        if HOOK_BEGIN in text:
            new = replace_region(text, HOOK_BEGIN, HOOK_END, block)
            if new == text:
                return f"unchanged ({where})"
            with open(hook, "w", encoding="utf-8") as fh:
                fh.write(new)
            chmod_x(hook)
            return f"regenerated managed block in {where}"
        if not text.endswith("\n"):
            text += "\n"
        with open(hook, "w", encoding="utf-8") as fh:
            fh.write(text + "\n" + block + "\n")
        chmod_x(hook)
        return f"appended managed block to existing {where}"
    with open(hook, "w", encoding="utf-8") as fh:
        fh.write("#!/usr/bin/env bash\n" + block + "\n")
    chmod_x(hook)
    return f"created {where}"


def _gitignore_block(rel: str, mode: str) -> str:
    if mode == "local":
        patterns = ["/.llm_resource_tally/local/"]
    else:
        # Ignore generated accounting state and the installed artifact, but keep the portable
        # policy visible so it can be committed and reused by fresh clones/workstations.
        patterns = [
            "/.llm_resource_tally/*",
            "!/.llm_resource_tally/settings.json",
        ]
    norm = rel.strip("/")
    if mode == "ignored" and norm and norm != "." and not norm.startswith(".llm_resource_tally/"):
        suffix = "/" if not os.path.splitext(norm)[1] else ""
        patterns.append(f"/{norm}{suffix}")
    return GITIGNORE_BEGIN + "\n" + "\n".join(dict.fromkeys(patterns)) + "\n" + GITIGNORE_END


def _managed_ignore_region(text: str) -> tuple[str, str] | None:
    if GITIGNORE_BEGIN in text and GITIGNORE_END in text:
        return GITIGNORE_BEGIN, GITIGNORE_END
    if LEGACY_GITIGNORE_BEGIN in text and LEGACY_GITIGNORE_END in text:
        return LEGACY_GITIGNORE_BEGIN, LEGACY_GITIGNORE_END
    return None


def _tracked_ignored_paths(root: str, rel: str) -> list[str]:
    specs = [".llm_resource_tally"]
    norm = rel.strip("/")
    if norm and not norm.startswith(".llm_resource_tally/"):
        specs.append(norm)
    try:
        text = git("ls-files", "--", *specs, cwd=root)
    except subprocess.CalledProcessError:
        return []
    return [line for line in text.splitlines() if line]


def configure_gitignore(root: str, rel: str, mode: str) -> str | None:
    """Maintain the explicit root ignore block for local/ignored storage."""
    path = os.path.join(root, ".gitignore")
    text = read_text(path)
    region = _managed_ignore_region(text)
    if mode in ("local", "ignored"):
        block = _gitignore_block(rel, mode)
        if region:
            new = replace_region(text, region[0], region[1], block)
        else:
            sep = (
                "" if not text else ("" if text.endswith("\n\n") else "\n" if text.endswith("\n") else "\n\n")
            )
            new = text + sep + block + "\n"
        changed = new != text
        if changed:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new)
        msg = "installed managed ignore block" if changed else "managed ignore block already current"
        tracked = (
            [p for p in _tracked_ignored_paths(root, rel) if p != ".llm_resource_tally/settings.json"]
            if mode == "ignored"
            else []
        )
        if tracked:
            specs = [".llm_resource_tally"]
            norm = rel.strip("/")
            if norm and not norm.startswith(".llm_resource_tally/"):
                specs.append(norm)
            git("rm", "-r", "-f", "--cached", "--ignore-unmatch", "--", *specs, cwd=root)
            settings = os.path.join(root, ".llm_resource_tally", "settings.json")
            if os.path.isfile(settings):
                git("add", "-f", "--", ".llm_resource_tally/settings.json", cwd=root)
            msg += (
                f"; staged removal of {len(tracked)} previously tracked generated path(s) "
                "while retaining settings.json"
            )
        return msg
    if region:
        start = text.index(region[0])
        end = text.index(region[1], start) + len(region[1])
        new = (text[:start].rstrip("\n") + "\n" + text[end:].lstrip("\n")).lstrip("\n")
        if new.strip():
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new if new.endswith("\n") else new + "\n")
        else:
            try:
                os.remove(path)
            except OSError:
                pass
        return "removed managed ignored-storage block"
    return None
