# SPDX-License-Identifier: Apache-2.0
"""Git post-commit hook wiring.

Owns everything about the `post-commit` hook that auto-records each commit: the self-locating
hook script, the vendored `hooks/` copy, the tool-dir `.gitignore`, and the choice between
sharing via `core.hooksPath` (clone-friendly) and appending a sentinel-guarded block to an
existing hook (so husky/lefthook/`.git/hooks` are never clobbered)."""
from __future__ import annotations

import os

from .gitutil import git
from .wiring_common import chmod_x, git_config, read_text, replace_region

# Self-locating post-commit written into `<dir>/hooks/` (used when core.hooksPath points there).
# `$here/..` is the package dir, which Python runs via its __main__.py.
SHARED_HOOK = (
    "#!/usr/bin/env bash\n"
    "# llm_resource_tally post-commit — auto-record LLM usage for the commit just made.\n"
    "# Self-locating; best-effort (accounting must never block or fail a commit).\n"
    'here="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)" || exit 0\n'
    'python3 "$here/.." record --commit HEAD >/dev/null 2>&1 || true\n'
)

HOOK_BEGIN = "# >>> llm_resource_tally (managed — regenerated by `install`) >>>"
HOOK_END = "# <<< llm_resource_tally (managed) <<<"

# Keep the vendored tool dir free of Python build cruft, so *running* the tool (which generates
# __pycache__/*.pyc beside the code) never dirties the host repo — regardless of whether the
# host's root .gitignore covers it. Scoped to the tool dir; the sibling ledger/ is unaffected.
TOOL_GITIGNORE = ("# llm_resource_tally: the vendored tool runs in place; ignore its bytecode\n"
                  "__pycache__/\n*.pyc\n")


def ensure_hook_file(root: str, rel: str) -> None:
    """Guarantee `<rel>/hooks/post-commit` exists (write from SHARED_HOOK if missing), so
    core.hooksPath share-mode has something to run."""
    hd = os.path.join(root, rel, "hooks")
    os.makedirs(hd, exist_ok=True)
    p = os.path.join(hd, "post-commit")
    if not os.path.exists(p):
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(SHARED_HOOK)
    chmod_x(p)


def ensure_tool_gitignore(root: str, rel: str) -> None:
    p = os.path.join(root, rel, ".gitignore")
    if not os.path.exists(p):
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(TOOL_GITIGNORE)


def _hook_block(rel: str) -> str:
    """Sentinel-wrapped post-commit body calling the vendored package by path. Best-effort
    (`|| true`); resolves the repo root at run time so it is correct from any cwd."""
    return (f"{HOOK_BEGIN}\n"
            f'root="$(git rev-parse --show-toplevel 2>/dev/null)" || root=""\n'
            f'[ -n "$root" ] && python3 "$root/{rel}" record '
            f"--commit HEAD >/dev/null 2>&1 || true\n"
            f"{HOOK_END}")


def hooks_dir_default(root: str) -> str:
    hd = git("rev-parse", "--git-path", "hooks", cwd=root)
    return hd if os.path.isabs(hd) else os.path.join(root, hd)


def _has_active_git_hooks(root: str) -> bool:
    hd = hooks_dir_default(root)
    if not os.path.isdir(hd):
        return False
    for name in os.listdir(hd):
        if name.endswith(".sample"):
            continue
        p = os.path.join(hd, name)
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return True
    return False


def effective_hooks_dir(root: str, existing_hp: str) -> str:
    if existing_hp:
        return existing_hp if os.path.isabs(existing_hp) else os.path.join(root, existing_hp)
    return hooks_dir_default(root)


def wire_hook(root: str, rel: str, mode: str) -> str:
    """auto: share via core.hooksPath if safe (unset + no foreign hooks) else append;
    hookspath: force core.hooksPath; append: force append; none: nothing."""
    if mode == "none":
        return "skipped (--hook-mode none)"
    existing_hp = git_config(root, "--get", "core.hooksPath")
    shared_dir = f"{rel}/hooks"

    if existing_hp and os.path.normpath(existing_hp) == os.path.normpath(shared_dir):
        chmod_x(os.path.join(root, shared_dir, "post-commit"))
        return f"already shared via core.hooksPath -> {shared_dir}"

    eff_hook = os.path.join(effective_hooks_dir(root, existing_hp), "post-commit")
    if os.path.exists(eff_hook) and HOOK_BEGIN in read_text(eff_hook):
        return _append_hook(root, rel, existing_hp)

    want_shared = mode == "hookspath" or (
        mode == "auto" and not existing_hp and not _has_active_git_hooks(root))
    if want_shared:
        git("config", "core.hooksPath", shared_dir, cwd=root)
        chmod_x(os.path.join(root, shared_dir, "post-commit"))
        return f"core.hooksPath -> {shared_dir} (committed; shared with everyone who clones)"
    return _append_hook(root, rel, existing_hp)


def _append_hook(root: str, rel: str, existing_hp: str) -> str:
    hd = effective_hooks_dir(root, existing_hp)
    os.makedirs(hd, exist_ok=True)
    hook = os.path.join(hd, "post-commit")
    where = os.path.relpath(hook, root)
    block = _hook_block(rel)
    if os.path.exists(hook):
        text = read_text(hook)
        if HOOK_BEGIN in text:
            new = replace_region(text, HOOK_BEGIN, HOOK_END, block)
            if new == text:
                return f"unchanged ({where})"
            with open(hook, "w", encoding="utf-8") as fh:
                fh.write(new)
            chmod_x(hook)
            return f"regenerated managed block in {where}"
        if not text.endswith("\n"):
            text += "\n"
        with open(hook, "w", encoding="utf-8") as fh:
            fh.write(text + "\n" + block + "\n")
        chmod_x(hook)
        return f"appended managed block to existing {where}"
    with open(hook, "w", encoding="utf-8") as fh:
        fh.write("#!/usr/bin/env bash\n" + block + "\n")
    chmod_x(hook)
    return f"created {where}"
