# SPDX-License-Identifier: Apache-2.0
"""The managed `AGENTS.md` block: a short, version-stamped note telling an agent that usage is
auto-recorded and that a fresh clone must run `install` once to arm the hook. Regenerated on
every `install`; found and replaced via the BEGIN/END sentinels so hand edits below it survive
and the block is never duplicated."""
from __future__ import annotations

import os
import re

from .wiring_common import read_text, strip_region

AGENTS_BEGIN = ("<!-- BEGIN llm_resource_tally v{version} (managed block — regenerated by "
                "`install`; edits below will be overwritten) -->")
AGENTS_END = "<!-- END llm_resource_tally -->"
AGENTS_BEGIN_RE = re.compile(
    r"<!--\s*BEGIN llm_resource_tally(?:\s+v([0-9][0-9A-Za-z.\-+]*))?.*?-->", re.S)

AGENTS_SNIPPET = """\
## LLM resource accounting
A git hook auto-records the tokens/model each commit costs to `.llm_resource_tally/` (measured
from the session transcript — never hand-edit or hand-count it). **After cloning, run
`{run} install` once** to arm it (git-local config isn't cloned). Non-committing work is swept
by `{run} reconcile`, automatic when the Claude session-end hook is wired."""


def _managed_agents_block(run: str, version: str) -> str:
    return (AGENTS_BEGIN.format(version=version) + "\n"
            + AGENTS_SNIPPET.format(run=run) + "\n" + AGENTS_END)


def install_agents_block(root: str, run: str, version: str, agents_name: str) -> str:
    path = os.path.join(root, agents_name)
    block = _managed_agents_block(run, version)
    if os.path.exists(path):
        text = read_text(path)
        m = AGENTS_BEGIN_RE.search(text)
        if m and AGENTS_END in text[m.end():]:
            old = m.group(1) or "?"
            e = text.index(AGENTS_END, m.end()) + len(AGENTS_END)
            new_text = text[:m.start()] + block + text[e:]
            if new_text == text:
                return f"already current (v{version})"
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_text)
            return (f"regenerated managed block (v{version})" if old == version
                    else f"upgraded managed block v{old} -> v{version}")
        sep = "\n" if text.endswith("\n") else "\n\n"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text + sep + block + "\n")
        return f"appended managed block (v{version})"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(f"# {agents_name}\n\n" + block + "\n")
    return f"created {agents_name} with managed block (v{version})"


def uninstall_agents_block(root: str, agents_name: str) -> str | None:
    """Strip our managed block from AGENTS.md, leaving any surrounding content. None if absent."""
    path = os.path.join(root, agents_name)
    if not os.path.exists(path):
        return None
    text = read_text(path)
    m = AGENTS_BEGIN_RE.search(text)
    if m and AGENTS_END in text[m.end():]:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(strip_region(text, m.start(), AGENTS_END))
        return f"stripped managed block from {agents_name}"
    return None
