# SPDX-License-Identifier: Apache-2.0
"""Git hook and storage-related worktree wiring."""
from __future__ import annotations

import os
import subprocess

from .gitutil import git
from .vendoring import is_source_checkout_path, shared_hooks_rel
from .wiring_common import chmod_x, git_config, read_text, replace_region

HOOK_BEGIN = "# >>> llm_resource_tally (managed — regenerated by `install`) >>>"
HOOK_END = "# <<< llm_resource_tally (managed) <<<"

TOOL_GITIGNORE = ("# llm_resource_tally: the vendored tool runs in place; ignore its bytecode\n"
                  "__pycache__/\n*.pyc\n")

GITIGNORE_BEGIN = "# >>> llm_resource_tally ignored storage (managed) >>>"
GITIGNORE_END = "# <<< llm_resource_tally ignored storage (managed) <<<"


def _shared_hook_text(rel: str) -> str:
    return (
        "#!/usr/bin/env bash\n"
        "# llm_resource_tally post-commit — best-effort measured usage recording.\n"
        'root="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0\n'
        f'python3 -B "$root/{rel}" record --commit HEAD >/dev/null 2>&1 || true\n'
    )


def ensure_hook_file(root: str, rel: str, hooks_rel: str | None = None) -> str:
    hooks_rel = hooks_rel or shared_hooks_rel(root, rel)
    hd = os.path.join(root, hooks_rel)
    os.makedirs(hd, exist_ok=True)
    path = os.path.join(hd, "post-commit")
    text = _shared_hook_text(rel)
    if read_text(path) != text:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
    chmod_x(path)
    return hooks_rel


def ensure_tool_gitignore(root: str, rel: str) -> None:
    """Keep bytecode out of a source install; zipapps cannot create package-local bytecode."""
    artifact = os.path.join(root, rel)
    if is_source_checkout_path(root, rel) or os.path.isfile(artifact) or rel.endswith(".pyz"):
        return
    p = os.path.join(artifact, ".gitignore")
    if not os.path.exists(p):
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(TOOL_GITIGNORE)


def _hook_block(rel: str) -> str:
    return (f"{HOOK_BEGIN}\n"
            f'root="$(git rev-parse --show-toplevel 2>/dev/null)" || root=""\n'
            f'[ -n "$root" ] && python3 -B "$root/{rel}" record '
            f"--commit HEAD >/dev/null 2>&1 || true\n"
            f"{HOOK_END}")


def hooks_dir_default(root: str) -> str:
    hd = git("rev-parse", "--git-path", "hooks", cwd=root)
    return hd if os.path.isabs(hd) else os.path.join(root, hd)


def _has_active_git_hooks(root: str) -> bool:
    hd = hooks_dir_default(root)
    if not os.path.isdir(hd):
        return False
    for name in os.listdir(hd):
        if name.endswith(".sample"):
            continue
        p = os.path.join(hd, name)
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return True
    return False


def effective_hooks_dir(root: str, existing_hp: str) -> str:
    if existing_hp:
        return existing_hp if os.path.isabs(existing_hp) else os.path.join(root, existing_hp)
    return hooks_dir_default(root)


def wire_hook(root: str, rel: str, mode: str, hooks_rel: str | None = None) -> str:
    if mode == "none":
        return "skipped (--hook-mode none)"
    hooks_rel = hooks_rel or shared_hooks_rel(root, rel)
    existing_hp = git_config(root, "--get", "core.hooksPath")
    if existing_hp and os.path.normpath(existing_hp) == os.path.normpath(hooks_rel):
        chmod_x(os.path.join(root, hooks_rel, "post-commit"))
        return f"already shared via core.hooksPath -> {hooks_rel}"

    eff_hook = os.path.join(effective_hooks_dir(root, existing_hp), "post-commit")
    existing_text = read_text(eff_hook) if os.path.exists(eff_hook) else ""
    if HOOK_BEGIN in existing_text:
        return _append_hook(root, rel, existing_hp)

    # A prior install may own core.hooksPath at a different artifact location (for example
    # source-tree -> zipapp conversion). Its standalone shared hook has this stable marker and
    # contains no user hook content, so auto mode can safely repoint to the newly generated hook.
    old_shared = bool(existing_hp and "llm_resource_tally post-commit" in existing_text)
    if old_shared and mode in ("auto", "hookspath"):
        git("config", "core.hooksPath", hooks_rel, cwd=root)
        chmod_x(os.path.join(root, hooks_rel, "post-commit"))
        return f"migrated core.hooksPath {existing_hp} -> {hooks_rel}"

    want_shared = mode == "hookspath" or (
        mode == "auto" and not existing_hp and not _has_active_git_hooks(root))
    if want_shared:
        git("config", "core.hooksPath", hooks_rel, cwd=root)
        chmod_x(os.path.join(root, hooks_rel, "post-commit"))
        return f"core.hooksPath -> {hooks_rel}"
    return _append_hook(root, rel, existing_hp)


def _append_hook(root: str, rel: str, existing_hp: str) -> str:
    hd = effective_hooks_dir(root, existing_hp)
    os.makedirs(hd, exist_ok=True)
    hook = os.path.join(hd, "post-commit")
    where = os.path.relpath(hook, root)
    block = _hook_block(rel)
    if os.path.exists(hook):
        text = read_text(hook)
        if HOOK_BEGIN in text:
            new = replace_region(text, HOOK_BEGIN, HOOK_END, block)
            if new == text:
                return f"unchanged ({where})"
            with open(hook, "w", encoding="utf-8") as fh:
                fh.write(new)
            chmod_x(hook)
            return f"regenerated managed block in {where}"
        if not text.endswith("\n"):
            text += "\n"
        with open(hook, "w", encoding="utf-8") as fh:
            fh.write(text + "\n" + block + "\n")
        chmod_x(hook)
        return f"appended managed block to existing {where}"
    with open(hook, "w", encoding="utf-8") as fh:
        fh.write("#!/usr/bin/env bash\n" + block + "\n")
    chmod_x(hook)
    return f"created {where}"


def _gitignore_block(rel: str) -> str:
    # Ignore generated accounting state and the installed artifact, but keep the portable policy
    # visible so it can be committed and reused by fresh clones/workstations.
    patterns = [
        "/.llm_resource_tally/*",
        "!/.llm_resource_tally/settings.json",
    ]
    norm = rel.strip("/")
    if norm and norm != "." and not norm.startswith(".llm_resource_tally/"):
        suffix = "/" if not os.path.splitext(norm)[1] else ""
        patterns.append(f"/{norm}{suffix}")
    return GITIGNORE_BEGIN + "\n" + "\n".join(dict.fromkeys(patterns)) + "\n" + GITIGNORE_END


def _tracked_ignored_paths(root: str, rel: str) -> list[str]:
    specs = [".llm_resource_tally"]
    norm = rel.strip("/")
    if norm and not norm.startswith(".llm_resource_tally/"):
        specs.append(norm)
    try:
        text = git("ls-files", "--", *specs, cwd=root)
    except subprocess.CalledProcessError:
        return []
    return [line for line in text.splitlines() if line]


def configure_gitignore(root: str, rel: str, mode: str) -> str | None:
    """Maintain an explicit root ignore block for ignored mode; remove it otherwise."""
    path = os.path.join(root, ".gitignore")
    text = read_text(path)
    if mode == "ignored":
        block = _gitignore_block(rel)
        if GITIGNORE_BEGIN in text and GITIGNORE_END in text:
            new = replace_region(text, GITIGNORE_BEGIN, GITIGNORE_END, block)
        else:
            sep = "" if not text else ("" if text.endswith("\n\n") else "\n" if text.endswith("\n") else "\n\n")
            new = text + sep + block + "\n"
        changed = new != text
        if changed:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new)
        msg = "installed managed ignore block" if changed else "managed ignore block already current"
        tracked = [p for p in _tracked_ignored_paths(root, rel)
                   if p != ".llm_resource_tally/settings.json"]
        if tracked:
            specs = [".llm_resource_tally"]
            norm = rel.strip("/")
            if norm and not norm.startswith(".llm_resource_tally/"):
                specs.append(norm)
            git("rm", "-r", "-f", "--cached", "--ignore-unmatch", "--", *specs, cwd=root)
            settings = os.path.join(root, ".llm_resource_tally", "settings.json")
            if os.path.isfile(settings):
                git("add", "-f", "--", ".llm_resource_tally/settings.json", cwd=root)
            msg += (f"; staged removal of {len(tracked)} previously tracked generated path(s) "
                    "while retaining settings.json")
        return msg
    if GITIGNORE_BEGIN in text and GITIGNORE_END in text:
        start = text.index(GITIGNORE_BEGIN)
        end = text.index(GITIGNORE_END, start) + len(GITIGNORE_END)
        new = (text[:start].rstrip("\n") + "\n" + text[end:].lstrip("\n")).lstrip("\n")
        if new.strip():
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new if new.endswith("\n") else new + "\n")
        else:
            try:
                os.remove(path)
            except OSError:
                pass
        return "removed managed ignored-storage block"
    return None
